# Generated by Django 3.2 on 2022-05-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
